#!/usr/bin/env bash
# This script displays all active IPv4 IPs

# Use ip command to show IPv4 addresses, then use grep to extract IP addresses
ip -4 addr show | grep -oP '(?<=inet\s)\d{1,3}(\.\d{1,3}){3}'
